temp disable stuff in test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -112,33 +112,34 @@ jobs:
       - name: Check clippy
         if: needs.changes.outputs.source == 'true'
         run: make check-clippy
-      - name: Check version
-        run: make check-version
-      - name: Check scripts
-        run: make check-scripts
-      - name: Check events
-        if: needs.changes.outputs.source == 'true'
-        run: make check-events
-      - name: Check cargo deny advisories/licenses
-        if: needs.changes.outputs.dependencies == 'true' || needs.changes.outputs.deny == 'true'
-        run: make check-deny
-      - name: Check Cue docs
-        if: needs.changes.outputs.cue == 'true'
-        run: make check-docs
-      - name: Check Markdown
-        if: needs.changes.outputs.markdown == 'true'
-        run: make check-markdown
-      - name: Check Component Docs
-        if: needs.changes.outputs.source == 'true' || needs.changes.outputs.component_docs == 'true'
-        run: make check-component-docs
-      - name: Check Rust Docs
-        if: needs.changes.outputs.source == 'true'
-        run: cd rust-doc && make docs
-      - uses: actions/upload-artifact@v3
-        with:
-          name: "config-schema.json"
-          path: "/tmp/vector-config-schema.json"
-        if: success() || failure()
+      # TODO temporary
+      # - name: Check version
+      #   run: make check-version
+      # - name: Check scripts
+      #   run: make check-scripts
+      # - name: Check events
+      #   if: needs.changes.outputs.source == 'true'
+      #   run: make check-events
+      # - name: Check cargo deny advisories/licenses
+      #   if: needs.changes.outputs.dependencies == 'true' || needs.changes.outputs.deny == 'true'
+      #   run: make check-deny
+      # - name: Check Cue docs
+      #   if: needs.changes.outputs.cue == 'true'
+      #   run: make check-docs
+      # - name: Check Markdown
+      #   if: needs.changes.outputs.markdown == 'true'
+      #   run: make check-markdown
+      # - name: Check Component Docs
+      #   if: needs.changes.outputs.source == 'true' || needs.changes.outputs.component_docs == 'true'
+      #   run: make check-component-docs
+      # - name: Check Rust Docs
+      #   if: needs.changes.outputs.source == 'true'
+      #   run: cd rust-doc && make docs
+      # - uses: actions/upload-artifact@v3
+      #   with:
+      #     name: "config-schema.json"
+      #     path: "/tmp/vector-config-schema.json"
+      #   if: success() || failure()
 
   master-failure:
     name: master-failure
